import type { Express, Request, Response } from "express";
import { z } from "zod";
import {
  SeatRequest,
  type InviteSeatResponse,
  type KeepSeatRefusedResponse,
  type MyRoomsResponse,
  type SeatEndedResponse,
  type SeatResponse,
} from "@vtt/shared";
import { hashToken } from "../domain/credentials";
import type { RoomRegistry } from "../domain/roomRegistry";
import { requireAccount } from "../identity/middleware";
import type { RoomStore } from "../store/roomStore";

const RoomIdParam = z.uuid();

/**
 * The membership layer's routes (ADR 0017 M2, M3, M5): resume a seat on any device, keep a guest
 * seat on the account, and list the account's rooms. Seats are handed out as fresh credentials
 * for the same participant, so the room kernel and the socket handshake don't change.
 */
export function registerMembershipRoutes(app: Express, deps: { store: RoomStore; registry: RoomRegistry }) {
  const { store, registry } = deps;

  /**
   * A new credential for the account's seat in the room, generated by the browser like a join's.
   * No room event, and the person's other devices keep theirs. A room the account holds no seat
   * in and does not own is the same 404 as a missing one.
   */
  app.post("/api/rooms/:roomId/seat", (req, res) => {
    void (async () => {
      res.setHeader("Cache-Control", "no-store");
      const account = requireAccount(res);
      if (!account) return;
      const roomId = RoomIdParam.safeParse(req.params.roomId);
      const body = SeatRequest.safeParse(req.body);
      if (!body.success) return void res.status(400).json({ error: "Invalid request" });
      const room = roomId.success ? await registry.get(roomId.data) : null;
      if (!roomId.success || !room || room.closed) return void notFound(res);

      let participantId = (await store.findMember(roomId.data, account.user.id))?.participantId;
      // The owner's GM seat, e.g. a room moved in from a legacy device that never had a seat on
      // the account: it joins the account on first open (ADR 0017 M2).
      if (!participantId && (await store.findRoomOwner(roomId.data)) === account.user.ownerId) {
        const gm = room.gmParticipant();
        if (gm) {
          await store.putMember({ roomId: roomId.data, participantId: gm.id, userId: account.user.id });
          participantId = gm.id;
        }
      }
      if (!participantId) return void notFound(res);

      const ended = room.endReason(participantId);
      if (ended === "left" || ended === "revoked") {
        const response: SeatEndedResponse = { error: ended === "left" ? "You left this room" : "You were removed from this room", reason: ended };
        return void res.status(403).json(response);
      }
      const participant = room.activeParticipant(participantId);
      if (!participant) return void notFound(res);

      await store.saveCredential(hashToken(body.data.guestToken), {
        roomId: roomId.data, participantId, sessionHash: account.session.tokenHash,
      });
      const response: SeatResponse = { roomId: roomId.data, participantId, role: participant.role };
      res.json(response);
    })().catch(internalError(req, res));
  });

  /**
   * Keeps this browser's guest seat on the account (ADR 0017 M3, §13.1's linking rules): proven by
   * the seat's credential (`Authorization: Bearer`) and the session together, for this room only,
   * the same participant, nothing changed in the room.
   */
  app.post("/api/rooms/:roomId/seat/keep", (req, res) => {
    void (async () => {
      const account = requireAccount(res);
      if (!account) return;
      const header = req.headers.authorization;
      const credentialHash = header?.startsWith("Bearer ") ? hashToken(header.slice(7)) : null;
      const credential = credentialHash ? await store.findCredential(credentialHash) : null;
      const room = credential && credential.roomId === req.params.roomId ? await registry.get(credential.roomId) : null;
      if (!credentialHash || !credential || !room || room.closed) return void notFound(res);

      const kept = await store.findMemberByParticipant(credential.roomId, credential.participantId);
      if (kept?.userId === account.user.id) return void res.status(204).end();
      if (room.endReason(credential.participantId)) {
        return void refuse(res, "seat_ended", "This seat has ended");
      }
      const conflict = await store.keepSeat(
        { roomId: credential.roomId, participantId: credential.participantId, userId: account.user.id },
        credentialHash,
        account.session.tokenHash,
      );
      if (conflict === "account_has_seat") {
        return void refuse(res, conflict, "Your account already has a seat in this room. The GM can move this seat's tokens to it.");
      }
      if (conflict === "seat_taken") return void refuse(res, conflict, "This seat is already kept on another account");
      res.status(204).end();
    })().catch(internalError(req, res));
  });

  /**
   * The account's active seat in an invite's room, so the invite page offers "Resume as Kim"
   * instead of a second join (room-membership). 404 when the account holds none there; a
   * signed-out visitor learns nothing (401).
   */
  app.get("/api/invites/:inviteCode/seat", (req, res) => {
    void (async () => {
      res.setHeader("Cache-Control", "no-store");
      const account = requireAccount(res);
      if (!account) return;
      const roomId = await store.findRoomByInvite(req.params.inviteCode);
      const room = roomId ? await registry.get(roomId) : null;
      const member = roomId && room && !room.closed ? await store.findMember(roomId, account.user.id) : null;
      const seat = member ? room!.activeParticipant(member.participantId) : undefined;
      if (!roomId || !seat) return void notFound(res);
      const response: InviteSeatResponse = { roomId, displayName: seat.displayName, role: seat.role };
      res.json(response);
    })().catch(internalError(req, res));
  });

  /** The rooms the account hosts, and the ones it holds an active player seat in (ADR 0017 M5). */
  app.get("/api/me/rooms", (req, res) => {
    void (async () => {
      res.setHeader("Cache-Control", "no-store");
      const account = requireAccount(res);
      if (!account) return;
      const hosting = await store.listOwnedRooms(account.user.ownerId);
      const hostingIds = new Set(hosting.map((r) => r.id));
      const playingIds: string[] = [];
      for (const member of await store.listMemberships(account.user.id)) {
        if (hostingIds.has(member.roomId)) continue;
        const room = await registry.get(member.roomId).catch(() => null);
        const seat = room && !room.closed ? room.activeParticipant(member.participantId) : undefined;
        if (seat?.role === "player") playingIds.push(member.roomId);
      }
      const response: MyRoomsResponse = { hosting, playing: await store.summarizeRooms(playingIds) };
      res.json(response);
    })().catch(internalError(req, res));
  });
}

function notFound(res: Response) {
  res.status(404).json({ error: "Room not found" });
}

function refuse(res: Response, reason: KeepSeatRefusedResponse["reason"], error: string) {
  res.status(409).json({ error, reason } satisfies KeepSeatRefusedResponse);
}

function internalError(req: Request, res: Response) {
  return (err: unknown) => {
    const route = (req.route as { path?: string } | undefined)?.path ?? "unknown route";
    console.error(`[vtt] ${req.method} ${route} failed:`, err);
    if (!res.headersSent) res.status(500).json({ error: "Internal error" });
  };
}
