import { randomUUID } from "node:crypto";
import path from "node:path";
import type { Express, Request } from "express";
import { z } from "zod";
import {
  CreateRoomRequest,
  JoinRoomRequest,
  HistoryQuery,
  HistoryResponse,
  activityHistory,
  type CreateRoomResponse,
  type InviteResponse,
  type JoinRoomResponse,
  type UploadResponse,
} from "@vtt/shared";
import { hashToken, newInviteCode } from "../domain/credentials";
import type { AssetStore } from "../store/assetStore";
import type { RoomRegistry } from "../domain/roomRegistry";
import type { RoomStore } from "../store/roomStore";
import { resolveGm } from "./gmAuth";
import { imageUploader } from "./imageUpload";
import { registerLibraryRoutes } from "./library";

/** Registers the REST API: rooms, invite joins, uploads, the library and GM history. */
export function registerRoutes(
  app: Express,
  deps: { store: RoomStore; registry: RoomRegistry; uploadDir: string; assets: AssetStore },
) {
  const { store, registry, uploadDir, assets } = deps;

  const receiveImage = imageUploader(uploadDir);

  // `/health` is what CI's smoke test and DESIGN.md §3 use; `/api/health` is reachable through the Vite proxy.
  const health = (_req: Request, res: { json: (body: unknown) => void }) => res.json({ ok: true });
  app.get("/health", health);
  app.get("/api/health", health);

  /**
   * Create a room; the caller becomes its GM.
   *
   * The credential is generated by the browser and only its SHA-256 reaches us
   * (DESIGN.md §5) — the server never holds a secret it could leak.
   * TODO(FR-GM-01): require an authenticated GM account. For now anyone may create a room.
   */
  app.post("/api/rooms", (req, res) => {
    void (async () => {
      const body = CreateRoomRequest.safeParse(req.body);
      if (!body.success) return res.status(400).json({ error: body.error.issues });
      if (!body.data.displayName.trim()) return res.status(400).json({ error: "Display name can't be blank." });

      const roomId = randomUUID();
      const inviteCode = newInviteCode();
      const participantId = randomUUID();
      // The GM device identity owns the room so the dashboard can list it (ADR 0004).
      const ownerGmId = body.data.gmToken ? await store.registerGm(hashToken(body.data.gmToken)) : null;

      await store.createRoom(roomId, inviteCode, { ownerGmId, name: body.data.roomName });
      await store.saveCredential(hashToken(body.data.guestToken), { roomId, participantId });
      const room = await registry.get(roomId);
      await room!.appendSystem(participantId, [
        { type: "RoomCreated", name: body.data.roomName },
        {
          type: "ParticipantJoined",
          participant: { id: participantId, role: "gm", displayName: body.data.displayName.trim() },
        },
      ]);
      const response: CreateRoomResponse = { roomId, inviteCode, participantId };
      return res.json(response);
    })().catch(() => res.status(500).json({ error: "Internal error" }));
  });

  /** Guest join from a shareable link (FR-PL-01). No account. */
  app.post("/api/invites/:inviteCode/join", (req, res) => {
    void (async () => {
      const body = JoinRoomRequest.safeParse(req.body);
      if (!body.success) return res.status(400).json({ error: body.error.issues });

      const roomId = await store.findRoomByInvite(req.params.inviteCode);
      const room = roomId ? await registry.get(roomId) : null;
      if (!roomId || !room || room.closed) return res.status(404).json({ error: "Invite not found" });

      const participantId = randomUUID();
      // Join first, credential second: a rejected join must leave no credential behind (KAN-61).
      const joined = await room.join({ id: participantId, role: "player", displayName: body.data.displayName });
      // not_found: the room was deleted while this join waited in its queue (ADR 0009).
      if (!joined.ok && joined.code === "not_found") return res.status(404).json({ error: "Invite not found" });
      if (!joined.ok) return res.status(joined.reason === "name_taken" ? 409 : 400).json({ error: joined.message });
      await store.saveCredential(hashToken(body.data.guestToken), { roomId, participantId });
      const response: JoinRoomResponse = { roomId, participantId };
      return res.json(response);
    })().catch(() => res.status(500).json({ error: "Internal error" }));
  });

  /** Image upload for maps/tokens. GM only (FR-GM-02). Stored in MinIO/S3 when configured. */
  app.post("/api/uploads", (req, res) => {
    void (async () => {
      const actor = await authenticate(req);
      if (!actor || actor.participant.role !== "gm") return res.status(403).json({ error: "GM only" });
      const upload = await receiveImage(req, res);
      if (!upload.ok) return res.status(upload.status).json({ error: upload.error });
      const key = path.basename(upload.file.path);
      const url = await assets.put(upload.file.path, key, upload.file.mimetype);
      // So deleting the room removes the image too (ADR 0009). If the room was deleted
      // since the check above, recording fails: remove the object rather than orphan it.
      try {
        await store.recordRoomUpload(actor.roomId, key);
      } catch (err) {
        await assets.delete(key).catch((cleanupErr: unknown) => {
          console.error(`[vtt] could not delete upload ${key} after its room upload record failed`, cleanupErr);
        });
        throw err;
      }
      const response: UploadResponse = { url };
      return res.json(response);
    })().catch(() => res.status(500).json({ error: "Internal error" }));
  });

  /**
   * The room's invite link, for its GM only (FR-GM-20). GET reads the current code; POST replaces
   * it, so a leaked link stops admitting anyone new. People already in the room are untouched.
   * Not an event: a code in the append-only log could be dug back out of history (design D6).
   */
  app.get("/api/rooms/:roomId/invite", (req, res) => {
    res.setHeader("Cache-Control", "no-store");
    void (async () => {
      if (!(await isRoomGm(req, req.params.roomId))) return res.status(403).json({ error: "GM only" });
      const inviteCode = await store.getInviteCode(req.params.roomId);
      if (!inviteCode) return res.status(404).json({ error: "Room not found" });
      const response: InviteResponse = { inviteCode };
      return res.json(response);
    })().catch(() => res.status(500).json({ error: "Internal error" }));
  });

  app.post("/api/rooms/:roomId/invite", (req, res) => {
    res.setHeader("Cache-Control", "no-store");
    void (async () => {
      if (!(await isRoomGm(req, req.params.roomId))) return res.status(403).json({ error: "GM only" });
      const response: InviteResponse = { inviteCode: await store.setInviteCode(req.params.roomId, newInviteCode) };
      return res.json(response);
    })().catch(() => res.status(500).json({ error: "Internal error" }));
  });

  /**
   * Deletes a room and everything scoped to it, for the GM identity that owns it (KAN-72,
   * ADR 0009). A room that is missing or someone else's is the same 404, so this can't be used
   * to probe room ids. Library assets are not the room's and are left alone.
   */
  app.delete("/api/rooms/:roomId", (req, res) => {
    void (async () => {
      const gm = await resolveGm(req, store);
      if (!gm) return res.status(401).json({ error: "GM identity required" });
      const roomId = req.params.roomId;
      const owned = z.uuid().safeParse(roomId).success && (await store.findRoomOwner(roomId)) === gm.gmId;
      if (!owned) return res.status(404).json({ error: "Room not found" });

      // Close first, so nothing commits into a room that is going away and nobody is left in it.
      await registry.close(roomId, "deleted");
      let deleted;
      try {
        deleted = await store.deleteRoom(roomId);
      } finally {
        // On failure too: the next access reloads the room from the store instead of finding it closed.
        registry.evict(roomId);
      }
      if (!deleted) return res.status(404).json({ error: "Room not found" });

      // After the commit, and best-effort: the room is gone, and a stray object has a random name.
      for (const key of deleted.uploadKeys) {
        await assets.delete(key).catch((err: unknown) => {
          console.error(`[vtt] could not delete upload ${key} of deleted room ${roomId}`, err);
        });
      }
      return res.status(204).end();
    })().catch(() => res.status(500).json({ error: "Internal error" }));
  });

  registerLibraryRoutes(app, { store, uploadDir, assets });

  /** FR-REC-01: history belongs to this room's GM, never merely any valid GM token. */
  app.get("/api/rooms/:roomId/history", (req, res) => {
    res.setHeader("Cache-Control", "no-store");
    void (async () => {
      const header = req.headers.authorization;
      const cred = header?.startsWith("Bearer ")
        ? await store.findCredential(hashToken(header.slice(7))) : null;
      if (!cred || cred.roomId !== req.params.roomId) return res.status(403).json({ error: "GM only" });
      const room = await registry.get(cred.roomId);
      const viewer = room?.activeParticipant(cred.participantId);
      if (!viewer || viewer.role !== "gm") return res.status(403).json({ error: "GM only" });
      const query = HistoryQuery.safeParse(req.query);
      if (!query.success) return res.status(400).json({ error: "Invalid history query" });
      const events = await store.loadEvents(cred.roomId);
      return res.json(HistoryResponse.parse(activityHistory(cred.roomId, events, viewer, query.data)));
    })().catch(() => res.status(500).json({ error: "Internal error" }));
  });

  /** True when the bearer credential is this room's GM, still in the room. */
  async function isRoomGm(req: Request, roomId: string) {
    const header = req.headers.authorization;
    if (!header?.startsWith("Bearer ")) return false;
    const cred = await store.findCredential(hashToken(header.slice(7)));
    if (!cred || cred.roomId !== roomId) return false;
    const room = await registry.get(cred.roomId);
    return room?.activeParticipant(cred.participantId)?.role === "gm";
  }

  /** The participant behind a bearer guest credential and their room, only while they are still in it. */
  async function authenticate(req: Request) {
    const header = req.headers.authorization;
    if (!header?.startsWith("Bearer ")) return null;
    const cred = await store.findCredential(hashToken(header.slice(7)));
    if (!cred) return null;
    const room = await registry.get(cred.roomId);
    const participant = room && !room.closed ? room.activeParticipant(cred.participantId) : undefined;
    return participant ? { roomId: cred.roomId, participant } : null;
  }
}
