import { randomUUID } from "node:crypto";
import path from "node:path";
import { unlink } from "node:fs/promises";
import type { Express, Request, Response } from "express";
import { z } from "zod";
import {
  ALREADY_MEMBER,
  CreateRoomRequest,
  DirectUploadFields,
  GridDetectionStatus,
  JoinRoomRequest,
  HistoryQuery,
  ROOM_FULL,
  HistoryResponse,
  activityHistory,
  emptyRoomState,
  encounterTable,
  tableOf,
  type CreateRoomResponse,
  type InviteResponse,
  type JoinRoomResponse,
  type ResolvedEncounter,
  type UploadResponse,
} from "@vtt/shared";
import { hashToken, newInviteCode } from "../domain/credentials";
import { resolveEncounter } from "../domain/encounterTemplates";
import type { AssetStore } from "../store/assetStore";
import type { RoomRegistry } from "../domain/roomRegistry";
import type { RoomStore } from "../store/roomStore";
import { requireAccount, signedIn } from "../identity/middleware";
import { refused, type AccountLimits } from "../identity/routes";
import { registerMembershipRoutes } from "../membership/routes";
import { registerDiceLookRoutes } from "../ownership/diceLooks";
import { registerLegacyRoutes } from "../ownership/legacy";
import { resolveOwner } from "../ownership/resolveOwner";
import { imageUploader } from "./imageUpload";
import { registerEncounterRoutes } from "./encounters";
import { registerLibraryRoutes } from "./library";
import { detectionWire } from "./library";
import { enqueueDetection, type GridDetectionDispatcher } from "../domain/gridDetection";
import type { DetectionTarget } from "../store/gridDetectionStore";

/** Registers the REST API: rooms, invite joins, uploads, the library and GM history. */
export function registerRoutes(
  app: Express,
  deps: { store: RoomStore; registry: RoomRegistry; uploadDir: string; assets: AssetStore; limits: AccountLimits; detection: GridDetectionDispatcher },
) {
  const { store, registry, uploadDir, assets, limits, detection } = deps;

  const receiveImage = imageUploader(uploadDir);

  // `/health` is what CI's smoke test and DESIGN.md §3 use; `/api/health` is reachable through the Vite proxy.
  const health = (_req: Request, res: { json: (body: unknown) => void }) => res.json({ ok: true });
  app.get("/health", health);
  app.get("/api/health", health);

  /**
   * Create a room; the signed-in caller becomes its GM (FR-GM-01: hosting requires an account,
   * DESIGN.md §13.1). The account owns the room, and the GM seat is kept on the account and bound
   * to this device's sign-in (ADR 0017 O1, M1, M4).
   *
   * The credential is generated by the browser and only its SHA-256 reaches us
   * (DESIGN.md §5) — the server never holds a secret it could leak.
   */
  app.post("/api/rooms", (req, res) => {
    void (async () => {
      const account = requireAccount(res);
      if (!account) return;
      const body = CreateRoomRequest.safeParse(req.body);
      if (!body.success) return res.status(400).json({ error: body.error.issues });
      if (!body.data.displayName.trim()) return res.status(400).json({ error: "Display name can't be blank." });

      // Resolved before anything is created, so a template that is gone leaves no half-made room (ADR 0024).
      let encounter: ResolvedEncounter | null = null;
      if (body.data.templateId) {
        const found = await resolveEncounter(store, account.user.ownerId, body.data.templateId);
        if (!found.ok) return res.status(found.reason === "missing" ? 404 : 409).json({ error: found.message });
        encounter = found.encounter;
      }

      const roomId = randomUUID();
      const inviteCode = newInviteCode();
      const participantId = randomUUID();

      await store.createRoom(roomId, inviteCode, { ownerGmId: account.user.ownerId, name: body.data.roomName });
      await store.saveCredential(hashToken(body.data.guestToken), {
        roomId, participantId, sessionHash: account.session.tokenHash,
      });
      await store.putMember({ roomId, participantId, userId: account.user.id });
      const room = await registry.get(roomId);
      await room!.appendSystem(participantId, [
        { type: "RoomCreated", name: body.data.roomName },
        {
          type: "ParticipantJoined",
          participant: { id: participantId, role: "gm", displayName: body.data.displayName.trim() },
        },
        ...(encounter
          ? [{
            type: "EncounterApplied" as const,
            templateId: encounter.id,
            name: encounter.name,
            applied: encounterTable(encounter, randomUUID),
            previous: tableOf(emptyRoomState(roomId)),
          }]
          : []),
      ]);
      const response: CreateRoomResponse = { roomId, inviteCode, participantId };
      return res.json(response);
    })().catch(internalError(req, res));
  });

  /**
   * Join from a shareable link (FR-PL-01). No account needed. A signed-in visitor gets the same
   * ordinary player seat, also kept on their account and bound to this device's sign-in
   * (ADR 0017 M1, M4); the room learns nothing about the account.
   */
  app.post("/api/invites/:inviteCode/join", (req, res) => {
    void (async () => {
      const body = JoinRoomRequest.safeParse(req.body);
      if (!body.success) return res.status(400).json({ error: body.error.issues });

      const roomId = await store.findRoomByInvite(req.params.inviteCode);
      const room = roomId ? await registry.get(roomId) : null;
      if (!roomId || !room || room.closed) return res.status(404).json({ error: "Invite not found" });
      // Every attempt counts, accepted or not: each join and its leave are permanent events, and
      // the player cap bounds seats held at once, not seats a room stores (security-hardening D2).
      const limit = limits.joinsPerIpPerRoom.hit(`join:${roomId}:${req.ip}`);
      if (refused(res, limit, "Too many joins from this address. Try again later.")) return;

      const account = signedIn(res);
      const participantId = randomUUID();
      // Join first, credential second: a rejected join must leave no credential behind (KAN-61).
      const joined = await room.join(
        { id: participantId, role: "player", displayName: body.data.displayName },
        account?.user.id,
      );
      // not_found: the room was deleted while this join waited in its queue (ADR 0009).
      if (!joined.ok && joined.code === "not_found") return res.status(404).json({ error: "Invite not found" });
      if (!joined.ok && joined.code === "already_member") {
        return res.status(409).json({ error: joined.message, code: ALREADY_MEMBER });
      }
      if (!joined.ok && joined.code === "removed") return res.status(403).json({ error: joined.message });
      // Already MAX_PLAYERS_PER_ROOM players at the table (room-player-cap).
      if (!joined.ok && joined.reason === "room_full") return res.status(409).json({ error: joined.message, code: ROOM_FULL });
      if (!joined.ok) return res.status(joined.reason === "name_taken" ? 409 : 400).json({ error: joined.message });
      await store.saveCredential(hashToken(body.data.guestToken), {
        roomId, participantId, sessionHash: account?.session.tokenHash ?? null,
      });
      const response: JoinRoomResponse = { roomId, participantId };
      return res.json(response);
    })().catch(internalError(req, res));
  });

  /** Image upload for maps/tokens. GM only (FR-GM-02). Stored in MinIO/S3 when configured. */
  app.post("/api/uploads", (req, res) => {
    void (async () => {
      const actor = await authenticate(req);
      if (!actor || actor.participant.role !== "gm") return res.status(403).json({ error: "GM only" });
      const upload = await receiveImage(req, res);
      if (!upload.ok) return res.status(upload.status).json({ error: upload.error });
      const fields = DirectUploadFields.safeParse(req.body);
      if (!fields.success) {
        await unlink(upload.file.path).catch(() => {});
        return res.status(400).json({ error: fields.error.issues });
      }
      const key = path.basename(upload.file.path);
      const url = await assets.put(upload.file.path, key, upload.file.mimetype);
      // So deleting the room removes the image too (ADR 0009). If the room was deleted
      // since the check above, recording fails: remove the object rather than orphan it.
      try {
        await store.recordRoomUpload(actor.roomId, key, fields.data.purpose, fields.data.width, fields.data.height);
      } catch (err) {
        await assets.delete(key).catch((cleanupErr: unknown) => {
          console.error(`[vtt] could not delete upload ${key} after its room upload record failed`, cleanupErr);
        });
        throw err;
      }
      if (fields.data.purpose === "map") await enqueueDetection(store, detection, { scope: "room", roomId: actor.roomId, objectKey: key }, 1);
      const response: UploadResponse = { url };
      return res.json(response);
    })().catch(internalError(req, res));
  });

  const currentDirectMap = async (roomId: string, expectedUrl: string | undefined): Promise<DetectionTarget | null> => {
    const room = await registry.get(roomId);
    const map = room?.currentMap();
    if (!map || map.url !== expectedUrl || map.assetId || !/^\/uploads\/[^/?#]+$/.test(map.url)) return null;
    return { scope: "room", roomId, objectKey: map.url.slice("/uploads/".length) };
  };

  app.get("/api/rooms/:roomId/grid-detection", (req, res) => {
    res.setHeader("Cache-Control", "no-store");
    void (async () => {
      if (!(await isRoomGm(req, req.params.roomId))) return res.status(403).json({ error: "GM only" });
      const target = await currentDirectMap(req.params.roomId, req.get("x-expected-map-url"));
      const row = target ? await store.findDetection(target) : null;
      if (!row) return res.status(404).json({ error: "No analysis for current map" });
      return res.json(detectionWire(row));
    })().catch(internalError(req, res));
  });

  app.post("/api/rooms/:roomId/grid-detection/retry", (req, res) => {
    res.setHeader("Cache-Control", "no-store");
    void (async () => {
      if (!(await isRoomGm(req, req.params.roomId))) return res.status(403).json({ error: "GM only" });
      const target = await currentDirectMap(req.params.roomId, req.get("x-expected-map-url"));
      if (!target || !(await store.findDetection(target))) return res.status(404).json({ error: "No analysis for current map" });
      const attempt = await store.retryDetection(target);
      if (!attempt) return res.status(409).json({ error: "Analysis is not in error" });
      await enqueueDetection(store, detection, target, attempt);
      const row = await store.findDetection(target);
      return res.status(202).json(GridDetectionStatus.parse(detectionWire(row!)));
    })().catch(internalError(req, res));
  });

  /**
   * The room's invite link, for its GM only (FR-GM-20). GET reads the current code; POST replaces
   * it, so a leaked link stops admitting anyone new. People already in the room are untouched.
   * Not an event: a code in the append-only log could be dug back out of history (design D6).
   */
  app.get("/api/rooms/:roomId/invite", (req, res) => {
    res.setHeader("Cache-Control", "no-store");
    void (async () => {
      if (!(await isRoomGm(req, req.params.roomId))) return res.status(403).json({ error: "GM only" });
      const inviteCode = await store.getInviteCode(req.params.roomId);
      if (!inviteCode) return res.status(404).json({ error: "Room not found" });
      const response: InviteResponse = { inviteCode };
      return res.json(response);
    })().catch(internalError(req, res));
  });

  app.post("/api/rooms/:roomId/invite", (req, res) => {
    res.setHeader("Cache-Control", "no-store");
    void (async () => {
      if (!(await isRoomGm(req, req.params.roomId))) return res.status(403).json({ error: "GM only" });
      const response: InviteResponse = { inviteCode: await store.setInviteCode(req.params.roomId, newInviteCode) };
      return res.json(response);
    })().catch(internalError(req, res));
  });

  /**
   * Deletes a room and everything scoped to it, for the owner (KAN-72, ADR 0009): the account, or
   * a legacy device identity, which may still delete what it has (ADR 0017). A room that is
   * missing or someone else's is the same 404, so this can't be used to probe room ids. Library
   * assets are not the room's and are left alone.
   */
  app.delete("/api/rooms/:roomId", (req, res) => {
    void (async () => {
      const owner = await resolveOwner(req, res, store);
      if (!owner) return res.status(401).json({ error: "Sign in to do that" });
      const roomId = req.params.roomId;
      const owned = z.uuid().safeParse(roomId).success && (await store.findRoomOwner(roomId)) === owner.ownerId;
      if (!owned) return res.status(404).json({ error: "Room not found" });

      // Close first, so nothing commits into a room that is going away and nobody is left in it.
      await registry.close(roomId, "deleted");
      let deleted;
      try {
        deleted = await store.deleteRoom(roomId);
      } finally {
        // On failure too: the next access reloads the room from the store instead of finding it closed.
        registry.evict(roomId);
      }
      if (!deleted) return res.status(404).json({ error: "Room not found" });

      // After the commit, and best-effort: the room is gone, and a stray object has a random name.
      for (const key of deleted.uploadKeys) {
        await assets.delete(key).catch((err: unknown) => {
          console.error(`[vtt] could not delete upload ${key} of deleted room ${roomId}`, err);
        });
      }
      return res.status(204).end();
    })().catch(internalError(req, res));
  });

  registerLibraryRoutes(app, { store, uploadDir, assets, detection });
  registerEncounterRoutes(app, { store, registry });
  registerLegacyRoutes(app, { store });
  registerDiceLookRoutes(app, { store, uploadDir, assets });
  registerMembershipRoutes(app, { store, registry });

  /** FR-REC-01: history belongs to this room's GM, never merely any valid GM token. */
  app.get("/api/rooms/:roomId/history", (req, res) => {
    res.setHeader("Cache-Control", "no-store");
    void (async () => {
      const header = req.headers.authorization;
      const cred = header?.startsWith("Bearer ")
        ? await store.findCredential(hashToken(header.slice(7))) : null;
      if (!cred || cred.roomId !== req.params.roomId) return res.status(403).json({ error: "GM only" });
      const room = await registry.get(cred.roomId);
      const viewer = room?.activeParticipant(cred.participantId);
      if (!viewer || viewer.role !== "gm") return res.status(403).json({ error: "GM only" });
      const query = HistoryQuery.safeParse(req.query);
      if (!query.success) return res.status(400).json({ error: "Invalid history query" });
      const events = await store.loadEvents(cred.roomId);
      return res.json(HistoryResponse.parse(activityHistory(cred.roomId, events, viewer, query.data)));
    })().catch(internalError(req, res));
  });

  /** True when the bearer credential is this room's GM, still in the room. */
  async function isRoomGm(req: Request, roomId: string) {
    const header = req.headers.authorization;
    if (!header?.startsWith("Bearer ")) return false;
    const cred = await store.findCredential(hashToken(header.slice(7)));
    if (!cred || cred.roomId !== roomId) return false;
    const room = await registry.get(cred.roomId);
    return room?.activeParticipant(cred.participantId)?.role === "gm";
  }

  /** The participant behind a bearer guest credential and their room, only while they are still in it. */
  async function authenticate(req: Request) {
    const header = req.headers.authorization;
    if (!header?.startsWith("Bearer ")) return null;
    const cred = await store.findCredential(hashToken(header.slice(7)));
    if (!cred) return null;
    const room = await registry.get(cred.roomId);
    const participant = room && !room.closed ? room.activeParticipant(cred.participantId) : undefined;
    return participant ? { roomId: cred.roomId, participant } : null;
  }
}

/**
 * The shared failure path for a REST handler: log what failed, then answer 500. A room whose
 * log won't replay lands here, so it costs one request, not the process (room-load-isolation).
 */
function internalError(req: Request, res: Response) {
  return (err: unknown) => {
    // The route pattern, not the URL: a join URL carries the invite code, which stays out of logs.
    const route = (req.route as { path?: string } | undefined)?.path ?? "unknown route";
    console.error(`[vtt] ${req.method} ${route} failed:`, err);
    if (!res.headersSent) res.status(500).json({ error: "Internal error" });
  };
}
