import { randomUUID } from "node:crypto";
import { mkdir } from "node:fs/promises";
import path from "node:path";
import type { Express, Request } from "express";
import multer from "multer";
import {
  CreateRoomRequest,
  JoinRoomRequest,
  type CreateRoomResponse,
  type JoinRoomResponse,
  type UploadResponse,
} from "@vtt/shared";
import { hashToken, newInviteCode } from "../domain/credentials";
import type { AssetStore } from "../store/assetStore";
import type { RoomRegistry } from "../domain/roomRegistry";
import type { RoomStore } from "../store/roomStore";

const IMAGE_TYPES: Record<string, string> = {
  "image/png": ".png",
  "image/jpeg": ".jpg",
  "image/webp": ".webp",
};

export function registerRoutes(
  app: Express,
  deps: { store: RoomStore; registry: RoomRegistry; uploadDir: string; assets: AssetStore },
) {
  const { store, registry, uploadDir, assets } = deps;

  const upload = multer({
    storage: multer.diskStorage({
      destination: (_req, _file, cb) => {
        void mkdir(uploadDir, { recursive: true }).then(
          () => cb(null, uploadDir),
          (err: Error) => cb(err, uploadDir),
        );
      },
      filename: (_req, file, cb) => cb(null, `${randomUUID()}${IMAGE_TYPES[file.mimetype] ?? ""}`),
    }),
    limits: { fileSize: 25 * 1024 * 1024, files: 1 },
    fileFilter: (_req, file, cb) => cb(null, Boolean(IMAGE_TYPES[file.mimetype])),
  });

  // `/health` is what CI's smoke test and DESIGN.md §3 use; `/api/health` is reachable through the Vite proxy.
  const health = (_req: Request, res: { json: (body: unknown) => void }) => res.json({ ok: true });
  app.get("/health", health);
  app.get("/api/health", health);

  /**
   * Create a room; the caller becomes its GM.
   *
   * The credential is generated by the browser and only its SHA-256 reaches us
   * (DESIGN.md §5) — the server never holds a secret it could leak.
   * TODO(FR-GM-01): require an authenticated GM account. For now anyone may create a room.
   */
  app.post("/api/rooms", (req, res) => {
    void (async () => {
      const body = CreateRoomRequest.safeParse(req.body);
      if (!body.success) return res.status(400).json({ error: body.error.issues });

      const roomId = randomUUID();
      const inviteCode = newInviteCode();
      const participantId = randomUUID();

      await store.createRoom(roomId, inviteCode);
      await store.saveCredential(hashToken(body.data.guestToken), { roomId, participantId });
      const room = await registry.get(roomId);
      await room!.appendSystem(participantId, [
        { type: "RoomCreated", name: body.data.roomName },
        {
          type: "ParticipantJoined",
          participant: { id: participantId, role: "gm", displayName: body.data.displayName },
        },
      ]);
      const response: CreateRoomResponse = { roomId, inviteCode, participantId };
      return res.json(response);
    })().catch(() => res.status(500).json({ error: "Internal error" }));
  });

  /** Guest join from a shareable link (FR-PL-01). No account. */
  app.post("/api/invites/:inviteCode/join", (req, res) => {
    void (async () => {
      const body = JoinRoomRequest.safeParse(req.body);
      if (!body.success) return res.status(400).json({ error: body.error.issues });

      const roomId = await store.findRoomByInvite(req.params.inviteCode);
      const room = roomId ? await registry.get(roomId) : null;
      if (!roomId || !room) return res.status(404).json({ error: "Invite not found" });

      const participantId = randomUUID();
      await store.saveCredential(hashToken(body.data.guestToken), { roomId, participantId });
      await room.appendSystem(participantId, [
        {
          type: "ParticipantJoined",
          participant: { id: participantId, role: "player", displayName: body.data.displayName },
        },
      ]);
      const response: JoinRoomResponse = { roomId, participantId };
      return res.json(response);
    })().catch(() => res.status(500).json({ error: "Internal error" }));
  });

  /** Image upload for maps/tokens. GM only (FR-GM-02). Stored in MinIO/S3 when configured. */
  app.post("/api/uploads", upload.single("file"), (req, res) => {
    void (async () => {
      const actor = await authenticate(req);
      if (!actor || actor.role !== "gm") return res.status(403).json({ error: "GM only" });
      if (!req.file) return res.status(415).json({ error: "Use PNG, JPEG or WebP" });
      const url = await assets.put(req.file.path, path.basename(req.file.path), req.file.mimetype);
      const response: UploadResponse = { url };
      return res.json(response);
    })().catch(() => res.status(500).json({ error: "Internal error" }));
  });

  async function authenticate(req: Request) {
    const header = req.headers.authorization;
    if (!header?.startsWith("Bearer ")) return null;
    const cred = await store.findCredential(hashToken(header.slice(7)));
    if (!cred) return null;
    const room = await registry.get(cred.roomId);
    return room?.participant(cred.participantId) ?? null;
  }
}
