import { z } from "zod";
import { Command } from "./commands";
import { CommittedEvent } from "./events";
import { GridSpec, Point } from "./geometry";
import { Id, Participant, type RoomState } from "./state";
import type { RejectionCode } from "./decide";

/**
 * WebSocket wire protocol. One socket per client carries two logical channels:
 *  - committed: commands in, ordered events out (persisted, sequenced)
 *  - ephemeral: pings/previews relayed to the room (never persisted, no seq) (FR-SYNC-03)
 */

// ---------- Ephemeral payloads ----------
export const EphemeralPayload = z.discriminatedUnion("type", [
  z.object({ type: z.literal("ping"), at: Point }),
  z.object({ type: z.literal("tokenDragPreview"), tokenId: Id, at: Point }),
]);
export type EphemeralPayload = z.infer<typeof EphemeralPayload>;

// ---------- Client -> Server ----------
/**
 * Socket.IO handshake credentials (`io(url, { auth })`).
 *
 * Identity is presented once per connection, not as a first message: Socket.IO
 * replays `auth` on every automatic reconnect, so a dropped client rebinds to the
 * same participant with no round trip (FR-PL-02, FR-PL-05). See docs/adr/0002.
 */
export const HandshakeAuth = z.object({
  roomId: Id,
  /** Opaque credential generated by the browser and kept in localStorage (DESIGN.md §5). */
  guestToken: z.string().min(16).max(256),
});
export type HandshakeAuth = z.infer<typeof HandshakeAuth>;

export const ClientMessage = z.discriminatedUnion("type", [
  z.object({
    type: z.literal("command"),
    /** Client-chosen id so the client can match the ack/rejection. */
    clientCommandId: z.string().min(1).max(64),
    command: Command,
  }),
  z.object({
    type: z.literal("ephemeral"),
    payload: EphemeralPayload,
  }),
  /** Client detected a seq gap or a reducer error; server replies with a fresh `welcome`. */
  z.object({ type: z.literal("resync") }),
]);
export type ClientMessage = z.infer<typeof ClientMessage>;
export type ClientMessageInput = z.input<typeof ClientMessage>;

// ---------- Server -> Client ----------
export type ServerMessage =
  /** Full, filtered snapshot. Client replaces its state and sets lastSeq = seq (FR-PL-06). */
  | { type: "welcome"; you: Participant; seq: number; state: RoomState }
  /** Next committed event. Client applies iff seq === lastSeq + 1, else sends `resync`. */
  | { type: "event"; committed: CommittedEvent }
  /** A seq the viewer may not see. Client advances lastSeq only. */
  | { type: "redacted"; seq: number }
  | { type: "ack"; clientCommandId: string; seq: number | null }
  | { type: "rejected"; clientCommandId: string; code: RejectionCode | "bad_request"; message: string }
  | { type: "ephemeral"; from: Id; payload: EphemeralPayload }
  /** Terminal: this seat has ended (ADR 0006). The server disconnects right after; do not reconnect. */
  | { type: "sessionEnded"; reason: "left" }
  | { type: "error"; code: "unauthorized" | "bad_request" | "not_found"; message: string };

/**
 * Socket.IO event names. One channel each way; the payload's own `type` discriminates.
 * Ephemeral traffic is sent with `volatile.emit` so it drops under backpressure
 * instead of queueing behind committed events (DESIGN.md §1, FR-SYNC-03).
 */
export const SOCKET_EVENTS = {
  /** Client -> server: a `ClientMessage`. */
  message: "message",
  /** Server -> client: a `ServerMessage`. */
  event: "event",
} as const;

// ---------- HTTP ----------
export const CreateRoomRequest = z.object({
  roomName: z.string().min(1).max(80),
  displayName: z.string().min(1).max(40),
  /** Browser-generated; the server stores only its SHA-256 (DESIGN.md §5). */
  guestToken: z.string().min(16).max(256),
  /** The creating browser's GM device token; when it resolves, the room is owned by it (ADR 0004). */
  gmToken: z.string().min(16).max(256).optional(),
});
export type CreateRoomRequest = z.infer<typeof CreateRoomRequest>;

export const JoinRoomRequest = z.object({
  displayName: z.string().min(1).max(40),
  /** Browser-generated; the server stores only its SHA-256 (DESIGN.md §5). */
  guestToken: z.string().min(16).max(256),
});
export type JoinRoomRequest = z.infer<typeof JoinRoomRequest>;

export interface RoomCredentials {
  roomId: string;
  participantId: string;
}

export interface CreateRoomResponse extends RoomCredentials {
  inviteCode: string;
}

export type JoinRoomResponse = RoomCredentials;

export interface UploadResponse {
  url: string;
}

// ---------- GM identity and asset library (ADR 0004) ----------

/** Browser-generated GM device token. The server stores only its SHA-256, like guest tokens. */
export const GmToken = z.string().min(16).max(256);

/** Header carrying the GM token until FR-GM-01 replaces it with a session cookie. */
export const GM_TOKEN_HEADER = "x-gm-token";

export const GmIdentifyRequest = z.object({ gmToken: GmToken });
export type GmIdentifyRequest = z.infer<typeof GmIdentifyRequest>;

export interface GmRoomSummary {
  id: string;
  name: string;
  /** ISO-8601 time of the room's most recent event. */
  lastActiveAt: string;
}

export const AssetKind = z.enum(["map", "token"]);
export type AssetKind = z.infer<typeof AssetKind>;

/** Largest image edge the library accepts, in pixels. */
export const MAX_ASSET_EDGE = 16384;

const AssetName = z.string().trim().min(1).max(80);
const Dimension = z.coerce.number().int().positive().max(MAX_ASSET_EDGE);

/** Text fields sent alongside the file in a multipart library upload. */
export const LibraryUploadFields = z.object({
  kind: AssetKind,
  name: AssetName,
  width: Dimension,
  height: Dimension,
});
export type LibraryUploadFields = z.infer<typeof LibraryUploadFields>;

export const LibraryPatchRequest = z
  .object({
    name: AssetName.optional(),
    /** Only valid for maps. */
    grid: GridSpec.optional(),
  })
  .refine((p) => p.name !== undefined || p.grid !== undefined, { message: "Nothing to change" });
export type LibraryPatchRequest = z.infer<typeof LibraryPatchRequest>;

export interface LibraryAsset {
  id: string;
  kind: AssetKind;
  name: string;
  /** Origin-relative image URL, same shape as `UploadResponse.url`. */
  url: string;
  width: number;
  height: number;
  /** Saved grid for maps; null for tokens. */
  grid: GridSpec | null;
  createdAt: string;
}

export interface LibraryUsageResponse {
  rooms: { id: string; name: string }[];
}
