import { z } from "zod";
import { TokenAttacks, type AttackPreset } from "./attackPresets";
import { Command, DEFAULT_TOKEN_COLOR } from "./commands";
import { CommittedEvent } from "./events";
import { GridSpec, Point } from "./geometry";
import { TokenStats, type ConditionId } from "./conditions";
import { AreaShape, Id, Participant, Token, type RoomState } from "./state";
import type { RejectionCode } from "./decide";

/**
 * WebSocket wire protocol. One socket per client carries two logical channels:
 *  - committed: commands in, ordered events out (persisted, sequenced)
 *  - ephemeral: pings/previews relayed to the room (never persisted, no seq) (FR-SYNC-03)
 */

// ---------- Ephemeral payloads ----------
export const EphemeralPayload = z.discriminatedUnion("type", [
  z.object({ type: z.literal("ping"), at: Point }),
  z.object({ type: z.literal("tokenDragPreview"), tokenId: Id, at: Point }),
  /**
   * A die let go over the map (ADR 0014): where it leaves the hand and where it lands, in board
   * coordinates. Sent just before the sender's `dice.roll`, so every other viewer can replay
   * the throw at the same spot when that roll arrives. Presentation only: never persisted, and
   * `expression` (as the server formats it) only pairs it with that roll.
   */
  z.object({ type: z.literal("diceDrop"), expression: z.string().min(1).max(32), from: Point, to: Point }),
  /**
   * An area template being aimed (KAN-35, ADR 0021), so the others watch it take shape. Null
   * clears it (placed or cancelled). One per sender; receivers also drop it a second after the
   * last update. Never persisted: only `template.place` commits.
   */
  z.object({
    type: z.literal("templatePreview"),
    preview: z.object({
      shape: AreaShape,
      origin: Point,
      toward: Point,
      size: z.number().positive().max(1000),
      width: z.number().positive().max(1000).optional(),
      gmOnly: z.boolean(),
    }).nullable(),
    /**
     * On a clear, whether the aim being cleared was GM-only, so players don't even learn of it.
     * Required on a clear: the server must never guess, or a GM's clear could reach players.
     */
    gmOnly: z.boolean().optional(),
  }).refine((p) => p.preview !== null || p.gmOnly !== undefined, { message: "A cleared aim must say whether it was GM-only", path: ["gmOnly"] }),
]);
export type EphemeralPayload = z.infer<typeof EphemeralPayload>;

// ---------- Client -> Server ----------
/**
 * Socket.IO handshake credentials (`io(url, { auth })`).
 *
 * Identity is presented once per connection, not as a first message: Socket.IO
 * replays `auth` on every automatic reconnect, so a dropped client rebinds to the
 * same participant with no round trip (FR-PL-02, FR-PL-05). See docs/adr/0002.
 */
export const HandshakeAuth = z.object({
  roomId: Id,
  /** Opaque credential generated by the browser and kept in localStorage (DESIGN.md §5). */
  guestToken: z.string().min(16).max(256),
});
export type HandshakeAuth = z.infer<typeof HandshakeAuth>;

export const ClientMessage = z.discriminatedUnion("type", [
  z.object({
    type: z.literal("command"),
    /** Client-chosen id so the client can match the ack/rejection. */
    clientCommandId: z.string().min(1).max(64),
    command: Command,
  }),
  z.object({
    type: z.literal("ephemeral"),
    payload: EphemeralPayload,
  }),
  /** Client detected a seq gap or a reducer error; server replies with a fresh `welcome`. */
  z.object({ type: z.literal("resync") }),
]);
export type ClientMessage = z.infer<typeof ClientMessage>;
export type ClientMessageInput = z.input<typeof ClientMessage>;

// ---------- Server -> Client ----------
/**
 * Why a seat ended (ADR 0006): the player left, or the GM removed them. Also the handshake error
 * text. `deleted` ends every seat at once, because the owner deleted the room (ADR 0009).
 */
/** `signed_out`: the sign-in this device's seat was bound to ended (ADR 0017 M4). */
export type SessionEndReason = "left" | "revoked" | "deleted" | "signed_out";

export type ServerMessage =
  /** Full, filtered snapshot. Client replaces its state and sets lastSeq = seq (FR-PL-06). */
  | { type: "welcome"; you: Participant; seq: number; state: RoomState }
  /** Next committed event. Client applies iff seq === lastSeq + 1, else sends `resync`. */
  | { type: "event"; committed: CommittedEvent }
  /** A seq the viewer may not see. Client advances lastSeq only. */
  | { type: "redacted"; seq: number }
  | { type: "ack"; clientCommandId: string; seq: number | null }
  | { type: "rejected"; clientCommandId: string; code: RejectionCode | "bad_request"; message: string }
  | { type: "ephemeral"; from: Id; payload: EphemeralPayload }
  /** Terminal: this seat has ended (ADR 0006). The server disconnects right after; do not reconnect. */
  | { type: "sessionEnded"; reason: SessionEndReason }
  | { type: "error"; code: "unauthorized" | "bad_request" | "not_found"; message: string };

/**
 * Socket.IO event names. One channel each way; the payload's own `type` discriminates.
 * Ephemeral traffic is sent with `volatile.emit` so it drops under backpressure
 * instead of queueing behind committed events (DESIGN.md §1, FR-SYNC-03).
 */
export const SOCKET_EVENTS = {
  /** Client -> server: a `ClientMessage`. */
  message: "message",
  /** Server -> client: a `ServerMessage`. */
  event: "event",
} as const;

// ---------- HTTP ----------
export const CreateRoomRequest = z.object({
  roomName: z.string().min(1).max(80),
  displayName: z.string().min(1).max(40),
  /** Browser-generated; the server stores only its SHA-256 (DESIGN.md §5). */
  guestToken: z.string().min(16).max(256),
  // `gmToken` was removed (ADR 0017): the signed-in account owns the room. zod strips unknown
  // keys, so an older client that still sends it parses unchanged.
});
export type CreateRoomRequest = z.infer<typeof CreateRoomRequest>;

export const JoinRoomRequest = z.object({
  displayName: z.string().min(1).max(40),
  /** Browser-generated; the server stores only its SHA-256 (DESIGN.md §5). */
  guestToken: z.string().min(16).max(256),
});
export type JoinRoomRequest = z.infer<typeof JoinRoomRequest>;

/** The 409 `code` for a join to a room that already holds `MAX_PLAYERS_PER_ROOM` players (room-player-cap). */
export const ROOM_FULL = "room_full";

export interface RoomCredentials {
  roomId: string;
  participantId: string;
}

export interface CreateRoomResponse extends RoomCredentials {
  inviteCode: string;
}

export type JoinRoomResponse = RoomCredentials;

/** `GET`/`POST /api/rooms/:roomId/invite`: the room's current invite code, GM only (FR-GM-20). */
export interface InviteResponse {
  inviteCode: string;
}

export interface UploadResponse {
  url: string;
}

// ---------- GM identity and asset library (ADR 0004) ----------

/**
 * Legacy GM device token (ADR 0004). No new ones are made since accounts (ADR 0017); an existing
 * one can still read, edit and delete what it owns, and be moved into an account.
 */
export const GmToken = z.string().min(16).max(256);

/** Header carrying a legacy GM device token. Accounts use the session cookie instead (ADR 0017). */
export const GM_TOKEN_HEADER = "x-gm-token";

/** Legacy: `POST /api/gm/identify` now answers 410 Gone (ADR 0017). */
export const GmIdentifyRequest = z.object({ gmToken: GmToken });
export type GmIdentifyRequest = z.infer<typeof GmIdentifyRequest>;

export interface GmRoomSummary {
  id: string;
  name: string;
  /** ISO-8601 time of the room's most recent event. */
  lastActiveAt: string;
}

export const AssetKind = z.enum(["map", "token"]);
export type AssetKind = z.infer<typeof AssetKind>;

/** Largest image edge the library accepts, in pixels. */
export const MAX_ASSET_EDGE = 16384;

const AssetName = z.string().trim().min(1).max(80);
const Dimension = z.coerce.number().int().positive().max(MAX_ASSET_EDGE);

/** Text fields sent alongside the file in a multipart library upload. */
export const LibraryUploadFields = z.object({
  kind: AssetKind,
  name: AssetName,
  width: Dimension,
  height: Dimension,
});
export type LibraryUploadFields = z.infer<typeof LibraryUploadFields>;

export const LibraryPatchRequest = z
  .object({
    name: AssetName.optional(),
    /** Only valid for maps. */
    grid: GridSpec.optional(),
  })
  .refine((p) => p.name !== undefined || p.grid !== undefined, { message: "Nothing to change" });
export type LibraryPatchRequest = z.infer<typeof LibraryPatchRequest>;

export interface LibraryAsset {
  id: string;
  kind: AssetKind;
  name: string;
  /** Origin-relative image URL, same shape as `UploadResponse.url`. */
  url: string;
  width: number;
  height: number;
  /** Saved grid for maps; null for tokens. */
  grid: GridSpec | null;
  createdAt: string;
}

export interface LibraryUsageResponse {
  rooms: { id: string; name: string }[];
  /** The GM's creatures that use this token art as their image (ADR 0012). */
  creatures: { id: string; name: string }[];
}

/**
 * A reusable creature in the GM's library (ADR 0012). Built from the token limits so a saved
 * creature always places as a valid `token.create`. The name is the name shown on the board.
 */
export const CreatureFields = z.object({
  name: Token.shape.name.refine((name) => name.trim() !== "", { message: "Name can't be blank" }),
  size: Token.shape.size,
  /** Starting HP; null/omitted preserves the legacy full-health default. */
  hp: TokenStats.shape.hp,
  attacks: TokenAttacks,
  maxHp: TokenStats.shape.maxHp,
  ac: TokenStats.shape.ac,
  /** The disc colour its tokens get when they have no image (KAN-70). */
  color: Token.shape.color,
  /** Conditions its tokens start with, e.g. Prone (KAN-70). No duplicates. */
  conditions: Token.shape.conditions.refine((c) => new Set(c).size === c.length, { message: "A condition is listed twice" }),
  /** The GM's own token art, or null for a plain colour disc. */
  imageAssetId: z.uuid().nullable(),
});

export const CreateCreatureRequest = CreatureFields.extend({
  size: Token.shape.size.default(1),
  hp: TokenStats.shape.hp.default(null),
  attacks: TokenAttacks.default([]),
  maxHp: TokenStats.shape.maxHp.default(null),
  ac: TokenStats.shape.ac.default(null),
  color: Token.shape.color.default(DEFAULT_TOKEN_COLOR),
  conditions: CreatureFields.shape.conditions.default([]),
  imageAssetId: z.uuid().nullable().default(null),
});
export type CreateCreatureRequest = z.infer<typeof CreateCreatureRequest>;

/** A saved template must place as a valid token rather than fail on HP > Max HP. */
export function creatureHpValid(creature: { hp: number | null; maxHp: number | null }): boolean {
  return creature.hp === null || creature.maxHp === null || creature.hp <= creature.maxHp;
}

export const UpdateCreatureRequest = CreatureFields.partial().refine((p) => Object.keys(p).length > 0, {
  message: "Nothing to change",
});
export type UpdateCreatureRequest = z.infer<typeof UpdateCreatureRequest>;

export interface LibraryCreature {
  id: string;
  name: string;
  size: number;
  /** Null or absent on older responses means start at Max HP. Zero is explicit. */
  hp?: number | null;
  attacks?: AttackPreset[];
  maxHp: number | null;
  ac: number | null;
  color: string;
  conditions: ConditionId[];
  imageAssetId: string | null;
  /** Resolved from the linked token art; null when there is none or it was deleted. */
  imageUrl: string | null;
  createdAt: string;
}
